### ISSUE TITLE
Notification email

### ISSUE THREAD

**Issue by webfactorybulgaria** [sibbell/support#39]
Our primary github email is used for accounting purposes - github payment notifications etc. They obviously don't need to be notified for any repository updates. Is there a way to send the notification to another email other than the primary github one?

**Comment by davegaeddert** [comment]
Hey @webfactorybulgaria, currently there's no way to change the email address that notifications go to -- but we do have this on our radar. Sorry, I know it seems like an obvious feature! As a sidenote, we actually don't get that many requests for this because most people log in with personal/user accounts which have their own email addresses, it looks like maybe @webfactorybulgaria is a user account but really serves as an organization?

**Comment by BobDankert** [comment]
This is something I would love to see as well.

**Comment by davegaeddert** [comment]
Haven't announced this yet formally, but in the new sibbell we now have the concept of "release monitors". You can choose the email address, Slack channel, or an RSS feed! 
http://help.sibbell.com/release-monitors/what-is-a-release-monitor
