### ISSUE TITLE
Releases not showing up in release list

### ISSUE THREAD

**Issue by adam-knights** [sibbell/support#48]
Nothing has shown up in my release list since March 17th (13 days ago).

Ember CLI is starred - and had a release 3 days -https://github.com/ember-cli/ember-cli/releases - this is not there.

Ember data is starred - and had a release 8 days ago - https://github.com/emberjs/data/releases

NPM is starred - and had a release 5 days ago - https://github.com/npm/npm/releases.

Screenshot of release list as of today:

![image](https://cloud.githubusercontent.com/assets/12710362/14138918/ab9ee2b0-f667-11e5-838f-b861df8eb9b4.png)

**Comment by tavrez** [comment]
Same for me, look like it's not checking for new versions anymore.

**Comment by adam-knights** [comment]
@davegaeddert could be wider thing if theres two of us starting to notice..

**Comment by matsev** [comment]
This seems to be a general issue.

The last version of the [aws-sdk-js](https://github.com/aws/aws-sdk-js) that Sibbell has picked up is v2.2.44 (see attached screenshot). Since then, AWS has published five more [releases](https://github.com/aws/aws-sdk-js/releases) (v2.2.45, v2.2.46, v2.2.47, v2.2.48 and v2.3.0) that has not been recorded Sibbell. According to GitHub, aws-sdk-js v2.2.44 was released 16 days ago and v2.2.45 was released 14 days ago, implying that the notifications stopped working some time between March 16 and 18.

![screen shot 2016-04-01 at 09 11 08](https://cloud.githubusercontent.com/assets/234505/14200318/56fff760-f7ea-11e5-9bfd-8eefe7e586ef.png)

**Comment by jean-christophe-manciot** [comment]
I have a mixed experience: I received a notification for debian apt 1.2.9 on the 27th of march, but last release of qemu/kvm (2.5.1 on 03/29) has not been notified for instance. Right now, the service is not reliable.
There is another issue when contacting https://sibbell.com/settings/, we get "Server error (500)". Cf. https://github.com/sibbell/sibbell-issues/issues/44
Also, there has been no answer from sibbell regarding the issues since ~ the first days of march.

**Comment by adam-knights** [comment]
I had an email for a release over the week, but it doesnt show up on the release website summary. So I would agree that release notifications are sometimes coming through - but more often than not they aren't

**Comment by davegaeddert** [comment]
Sorry for the trouble -- I'll refer you to this comment about what's going on with Sibbell in general: https://github.com/sibbell/sibbell-issues/issues/44#issuecomment-208526678

I'll try to keep it functioning a little more reliably going forward...

**Comment by davegaeddert** [comment]
The newly rebuilt sibbell.com should be much more reliable in this regard (and just about everything else).
