### ISSUE TITLE
Mattermost support

### ISSUE THREAD

**Issue by Bacto** [sibbell/support#78]
Hi guys,

First I would like to thank you for your work :)

Second, I would like to add an alert to Mattermost, an open source clone of Slack.
What is awesome is that there API is compatible with the Slack's API.
What is not awesome is that you limit your interface to URL starting by "https://hooks.slack.com" :

<img width="898" alt="capture d ecran 2017-02-26 a 17 08 42" src="https://cloud.githubusercontent.com/assets/1188497/23369960/61547e6e-fd13-11e6-9719-c9e8529b9a6a.png">

It would be awesome to accept custom URL to support Mattermost :)

Thanks,
Adrien

**Comment by davegaeddert** [comment]
Quick update on this -- we're not planning to add Mattermost support specifically. Unfortunately Sibbell Pro hasn't really worked out in terms of getting Sibbell to have some revenue (which we need to justify working on new features like this). I'd encourage you to look at https://www.dependencies.io though, which is something we spun out of a lot of Sibbell questions/suggestions. In fact, you can probably already use Mattermost with our Slack "actor" on dependencies.io since it doesn't check that it is a Slack-specific url ;)
